addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"         % "0.9.21")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.14")
addSbtPlugin("io.spray"                  % "sbt-revolver"         % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"  % "1.7.6")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "0.15.0")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.10.0-RC1")
